#include "rtbot_sql/compiler/graph_builder.h"

#include <nlohmann/json.hpp>
#include <set>

using json = nlohmann::json;

namespace rtbot_sql::compiler {

std::string GraphBuilder::next_id(const std::string& prefix) {
  return prefix + "_" + std::to_string(id_counter_++);
}

void GraphBuilder::add_operator(
    const std::string& id, const std::string& type,
    const std::map<std::string, double>& params,
    const std::map<std::string, std::string>& string_params,
    const std::map<std::string, std::vector<double>>& double_array_params,
    const std::map<std::string, std::vector<int>>& int_array_params) {
  operators_.push_back(
      {id, type, params, string_params, double_array_params, int_array_params});
}

void GraphBuilder::connect(const Endpoint& from, const Endpoint& to) {
  connections_.push_back(
      {from.operator_id, from.port, to.operator_id, to.port});
}

void GraphBuilder::add_prototype(const PrototypeDef& proto) {
  prototypes_.push_back(proto);
}

const OperatorDef* GraphBuilder::find_operator(const std::string& id) const {
  for (const auto& op : operators_) {
    if (op.id == id) return &op;
  }
  return nullptr;
}

const PrototypeDef* GraphBuilder::find_prototype(
    const std::string& id) const {
  for (const auto& p : prototypes_) {
    if (p.id == id) return &p;
  }
  return nullptr;
}

namespace {

static const std::set<std::string> int_params = {
    "index", "numPorts", "window", "window_size", "interval", "key_index"};

json operator_to_json(const OperatorDef& op) {
  json j;
  j["id"] = op.id;
  j["type"] = op.type;

  if (op.type == "Input" || op.type == "Output") {
    j["portTypes"] = json::array({"vector_number"});
  }

  for (const auto& [key, val] : op.params) {
    if (int_params.count(key)) {
      j[key] = static_cast<int>(val);
    } else {
      j[key] = val;
    }
  }
  for (const auto& [key, val] : op.string_params) {
    j[key] = val;
  }
  for (const auto& [key, vals] : op.double_array_params) {
    j[key] = vals;
  }
  for (const auto& [key, vals] : op.int_array_params) {
    j[key] = vals;
  }

  return j;
}

json connection_to_json(const Connection& c) {
  return {{"from", c.from_id},
          {"fromPort", c.from_port},
          {"to", c.to_id},
          {"toPort", c.to_port}};
}

json prototype_to_json(const PrototypeDef& proto) {
  json j;
  j["entry"] = {{"operator", proto.entry_id}};
  j["output"] = {{"operator", proto.output_id}};

  j["operators"] = json::array();
  for (const auto& op : proto.operators) {
    j["operators"].push_back(operator_to_json(op));
  }

  j["connections"] = json::array();
  for (const auto& c : proto.connections) {
    j["connections"].push_back(connection_to_json(c));
  }

  return j;
}

}  // namespace

std::string GraphBuilder::to_json() const {
  // Build prototype lookup by ID
  std::map<std::string, const PrototypeDef*> proto_map;
  for (const auto& p : prototypes_) {
    proto_map[p.id] = &p;
  }

  // Find entry and output operator IDs
  std::string entry_id, output_id;
  for (const auto& op : operators_) {
    if (op.type == "Input") entry_id = op.id;
    if (op.type == "Output") output_id = op.id;
  }

  json program;
  program["title"] = "<auto-generated>";
  if (!entry_id.empty()) {
    program["entryOperator"] = entry_id;
  }
  if (!output_id.empty()) {
    program["output"] = {{output_id, json::array({"o1"})}};
  }

  program["operators"] = json::array();
  for (const auto& op : operators_) {
    if (op.type == "KeyedPipeline") {
      // Build operator JSON, inlining the referenced prototype
      json j = operator_to_json(op);
      j.erase("prototype");  // remove the string ref

      auto proto_it = op.string_params.find("prototype");
      if (proto_it != op.string_params.end()) {
        auto pm_it = proto_map.find(proto_it->second);
        if (pm_it != proto_map.end()) {
          j["prototype"] = prototype_to_json(*pm_it->second);
        }
      }
      program["operators"].push_back(j);
    } else {
      program["operators"].push_back(operator_to_json(op));
    }
  }

  program["connections"] = json::array();
  for (const auto& c : connections_) {
    program["connections"].push_back(connection_to_json(c));
  }

  return program.dump(2);
}

}  // namespace rtbot_sql::compiler
