cc_binary(
    name = "ims_cpp_benchmark",
    srcs = ["ims_cpp_benchmark.cpp"],
    deps = [
        "//libs/api:api_compiler",
        "@json-cpp//:lib",
        "@rtbot//libs/api:rtbot-api",
    ],
)

cc_binary(
    name = "ims_debug_test",
    srcs = ["ims_debug_test.cpp"],
    deps = [
        "//libs/api:api_compiler",
        "@rtbot//libs/api:rtbot-api",
    ],
)
